// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: response_generic.proto
// Protobuf Java Version: 4.29.2

package com.sepp89117.goeasypro_android.gopro;

public final class ResponseGenericOuterClass {
  private ResponseGenericOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      ResponseGenericOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.sepp89117.goeasypro_android.gopro.EnumResultGeneric}
   */
  public enum EnumResultGeneric
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RESULT_UNKNOWN = 0;</code>
     */
    RESULT_UNKNOWN(0),
    /**
     * <code>RESULT_SUCCESS = 1;</code>
     */
    RESULT_SUCCESS(1),
    /**
     * <code>RESULT_ILL_FORMED = 2;</code>
     */
    RESULT_ILL_FORMED(2),
    /**
     * <code>RESULT_NOT_SUPPORTED = 3;</code>
     */
    RESULT_NOT_SUPPORTED(3),
    /**
     * <code>RESULT_ARGUMENT_OUT_OF_BOUNDS = 4;</code>
     */
    RESULT_ARGUMENT_OUT_OF_BOUNDS(4),
    /**
     * <code>RESULT_ARGUMENT_INVALID = 5;</code>
     */
    RESULT_ARGUMENT_INVALID(5),
    /**
     * <code>RESULT_RESOURCE_NOT_AVAILABLE = 6;</code>
     */
    RESULT_RESOURCE_NOT_AVAILABLE(6),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        EnumResultGeneric.class.getName());
    }
    /**
     * <code>RESULT_UNKNOWN = 0;</code>
     */
    public static final int RESULT_UNKNOWN_VALUE = 0;
    /**
     * <code>RESULT_SUCCESS = 1;</code>
     */
    public static final int RESULT_SUCCESS_VALUE = 1;
    /**
     * <code>RESULT_ILL_FORMED = 2;</code>
     */
    public static final int RESULT_ILL_FORMED_VALUE = 2;
    /**
     * <code>RESULT_NOT_SUPPORTED = 3;</code>
     */
    public static final int RESULT_NOT_SUPPORTED_VALUE = 3;
    /**
     * <code>RESULT_ARGUMENT_OUT_OF_BOUNDS = 4;</code>
     */
    public static final int RESULT_ARGUMENT_OUT_OF_BOUNDS_VALUE = 4;
    /**
     * <code>RESULT_ARGUMENT_INVALID = 5;</code>
     */
    public static final int RESULT_ARGUMENT_INVALID_VALUE = 5;
    /**
     * <code>RESULT_RESOURCE_NOT_AVAILABLE = 6;</code>
     */
    public static final int RESULT_RESOURCE_NOT_AVAILABLE_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumResultGeneric valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumResultGeneric forNumber(int value) {
      switch (value) {
        case 0: return RESULT_UNKNOWN;
        case 1: return RESULT_SUCCESS;
        case 2: return RESULT_ILL_FORMED;
        case 3: return RESULT_NOT_SUPPORTED;
        case 4: return RESULT_ARGUMENT_OUT_OF_BOUNDS;
        case 5: return RESULT_ARGUMENT_INVALID;
        case 6: return RESULT_RESOURCE_NOT_AVAILABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumResultGeneric>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumResultGeneric> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumResultGeneric>() {
            public EnumResultGeneric findValueByNumber(int number) {
              return EnumResultGeneric.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final EnumResultGeneric[] VALUES = values();

    public static EnumResultGeneric valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumResultGeneric(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.sepp89117.goeasypro_android.gopro.EnumResultGeneric)
  }

  public interface ResponseGenericOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sepp89117.goeasypro_android.gopro.ResponseGeneric)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Generic pass/fail/error info
     * </pre>
     *
     * <code>required .com.sepp89117.goeasypro_android.gopro.EnumResultGeneric result = 1;</code>
     * @return Whether the result field is set.
     */
    boolean hasResult();
    /**
     * <pre>
     * Generic pass/fail/error info
     * </pre>
     *
     * <code>required .com.sepp89117.goeasypro_android.gopro.EnumResultGeneric result = 1;</code>
     * @return The result.
     */
    com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric getResult();
  }
  /**
   * <pre>
   *
   * Generic Response used across many response / notification messages
   * </pre>
   *
   * Protobuf type {@code com.sepp89117.goeasypro_android.gopro.ResponseGeneric}
   */
  public static final class ResponseGeneric extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.sepp89117.goeasypro_android.gopro.ResponseGeneric)
      ResponseGenericOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        ResponseGeneric.class.getName());
    }
    // Use ResponseGeneric.newBuilder() to construct.
    private ResponseGeneric(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResponseGeneric() {
      result_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.internal_static_com_sepp89117_goeasypro_android_gopro_ResponseGeneric_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.internal_static_com_sepp89117_goeasypro_android_gopro_ResponseGeneric_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric.class, com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric.Builder.class);
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_ = 0;
    /**
     * <pre>
     * Generic pass/fail/error info
     * </pre>
     *
     * <code>required .com.sepp89117.goeasypro_android.gopro.EnumResultGeneric result = 1;</code>
     * @return Whether the result field is set.
     */
    @java.lang.Override public boolean hasResult() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Generic pass/fail/error info
     * </pre>
     *
     * <code>required .com.sepp89117.goeasypro_android.gopro.EnumResultGeneric result = 1;</code>
     * @return The result.
     */
    @java.lang.Override public com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric getResult() {
      com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric result = com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric.forNumber(result_);
      return result == null ? com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric.RESULT_UNKNOWN : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric)) {
        return super.equals(obj);
      }
      com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric other = (com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric) obj;

      if (hasResult() != other.hasResult()) return false;
      if (hasResult()) {
        if (result_ != other.result_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + result_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *
     * Generic Response used across many response / notification messages
     * </pre>
     *
     * Protobuf type {@code com.sepp89117.goeasypro_android.gopro.ResponseGeneric}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sepp89117.goeasypro_android.gopro.ResponseGeneric)
        com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGenericOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.internal_static_com_sepp89117_goeasypro_android_gopro_ResponseGeneric_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.internal_static_com_sepp89117_goeasypro_android_gopro_ResponseGeneric_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric.class, com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric.Builder.class);
      }

      // Construct using com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        result_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.internal_static_com_sepp89117_goeasypro_android_gopro_ResponseGeneric_descriptor;
      }

      @java.lang.Override
      public com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric getDefaultInstanceForType() {
        return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric.getDefaultInstance();
      }

      @java.lang.Override
      public com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric build() {
        com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric buildPartial() {
        com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric result = new com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.result_ = result_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric) {
          return mergeFrom((com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric other) {
        if (other == com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasResult()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric tmpValue =
                    com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(1, tmpRaw);
                } else {
                  result_ = tmpRaw;
                  bitField0_ |= 0x00000001;
                }
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int result_ = 0;
      /**
       * <pre>
       * Generic pass/fail/error info
       * </pre>
       *
       * <code>required .com.sepp89117.goeasypro_android.gopro.EnumResultGeneric result = 1;</code>
       * @return Whether the result field is set.
       */
      @java.lang.Override public boolean hasResult() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Generic pass/fail/error info
       * </pre>
       *
       * <code>required .com.sepp89117.goeasypro_android.gopro.EnumResultGeneric result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric getResult() {
        com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric result = com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric.forNumber(result_);
        return result == null ? com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric.RESULT_UNKNOWN : result;
      }
      /**
       * <pre>
       * Generic pass/fail/error info
       * </pre>
       *
       * <code>required .com.sepp89117.goeasypro_android.gopro.EnumResultGeneric result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.EnumResultGeneric value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Generic pass/fail/error info
       * </pre>
       *
       * <code>required .com.sepp89117.goeasypro_android.gopro.EnumResultGeneric result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sepp89117.goeasypro_android.gopro.ResponseGeneric)
    }

    // @@protoc_insertion_point(class_scope:com.sepp89117.goeasypro_android.gopro.ResponseGeneric)
    private static final com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric();
    }

    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseGeneric>
        PARSER = new com.google.protobuf.AbstractParser<ResponseGeneric>() {
      @java.lang.Override
      public ResponseGeneric parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResponseGeneric> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseGeneric> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.ResponseGeneric getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MediaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sepp89117.goeasypro_android.gopro.Media)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Directory in which the media is contained
     * </pre>
     *
     * <code>optional string folder = 1;</code>
     * @return Whether the folder field is set.
     */
    boolean hasFolder();
    /**
     * <pre>
     * Directory in which the media is contained
     * </pre>
     *
     * <code>optional string folder = 1;</code>
     * @return The folder.
     */
    java.lang.String getFolder();
    /**
     * <pre>
     * Directory in which the media is contained
     * </pre>
     *
     * <code>optional string folder = 1;</code>
     * @return The bytes for folder.
     */
    com.google.protobuf.ByteString
        getFolderBytes();

    /**
     * <pre>
     * Filename of media
     * </pre>
     *
     * <code>optional string file = 2;</code>
     * @return Whether the file field is set.
     */
    boolean hasFile();
    /**
     * <pre>
     * Filename of media
     * </pre>
     *
     * <code>optional string file = 2;</code>
     * @return The file.
     */
    java.lang.String getFile();
    /**
     * <pre>
     * Filename of media
     * </pre>
     *
     * <code>optional string file = 2;</code>
     * @return The bytes for file.
     */
    com.google.protobuf.ByteString
        getFileBytes();
  }
  /**
   * <pre>
   * *
   * A common model to represent a media file
   * </pre>
   *
   * Protobuf type {@code com.sepp89117.goeasypro_android.gopro.Media}
   */
  public static final class Media extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.sepp89117.goeasypro_android.gopro.Media)
      MediaOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        Media.class.getName());
    }
    // Use Media.newBuilder() to construct.
    private Media(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Media() {
      folder_ = "";
      file_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.internal_static_com_sepp89117_goeasypro_android_gopro_Media_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.internal_static_com_sepp89117_goeasypro_android_gopro_Media_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media.class, com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media.Builder.class);
    }

    private int bitField0_;
    public static final int FOLDER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object folder_ = "";
    /**
     * <pre>
     * Directory in which the media is contained
     * </pre>
     *
     * <code>optional string folder = 1;</code>
     * @return Whether the folder field is set.
     */
    @java.lang.Override
    public boolean hasFolder() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Directory in which the media is contained
     * </pre>
     *
     * <code>optional string folder = 1;</code>
     * @return The folder.
     */
    @java.lang.Override
    public java.lang.String getFolder() {
      java.lang.Object ref = folder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          folder_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Directory in which the media is contained
     * </pre>
     *
     * <code>optional string folder = 1;</code>
     * @return The bytes for folder.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFolderBytes() {
      java.lang.Object ref = folder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        folder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object file_ = "";
    /**
     * <pre>
     * Filename of media
     * </pre>
     *
     * <code>optional string file = 2;</code>
     * @return Whether the file field is set.
     */
    @java.lang.Override
    public boolean hasFile() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Filename of media
     * </pre>
     *
     * <code>optional string file = 2;</code>
     * @return The file.
     */
    @java.lang.Override
    public java.lang.String getFile() {
      java.lang.Object ref = file_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          file_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Filename of media
     * </pre>
     *
     * <code>optional string file = 2;</code>
     * @return The bytes for file.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileBytes() {
      java.lang.Object ref = file_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        file_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, folder_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, file_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, folder_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, file_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media)) {
        return super.equals(obj);
      }
      com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media other = (com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media) obj;

      if (hasFolder() != other.hasFolder()) return false;
      if (hasFolder()) {
        if (!getFolder()
            .equals(other.getFolder())) return false;
      }
      if (hasFile() != other.hasFile()) return false;
      if (hasFile()) {
        if (!getFile()
            .equals(other.getFile())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFolder()) {
        hash = (37 * hash) + FOLDER_FIELD_NUMBER;
        hash = (53 * hash) + getFolder().hashCode();
      }
      if (hasFile()) {
        hash = (37 * hash) + FILE_FIELD_NUMBER;
        hash = (53 * hash) + getFile().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * *
     * A common model to represent a media file
     * </pre>
     *
     * Protobuf type {@code com.sepp89117.goeasypro_android.gopro.Media}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sepp89117.goeasypro_android.gopro.Media)
        com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.MediaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.internal_static_com_sepp89117_goeasypro_android_gopro_Media_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.internal_static_com_sepp89117_goeasypro_android_gopro_Media_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media.class, com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media.Builder.class);
      }

      // Construct using com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        folder_ = "";
        file_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.internal_static_com_sepp89117_goeasypro_android_gopro_Media_descriptor;
      }

      @java.lang.Override
      public com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media getDefaultInstanceForType() {
        return com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media.getDefaultInstance();
      }

      @java.lang.Override
      public com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media build() {
        com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media buildPartial() {
        com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media result = new com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.folder_ = folder_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.file_ = file_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media) {
          return mergeFrom((com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media other) {
        if (other == com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media.getDefaultInstance()) return this;
        if (other.hasFolder()) {
          folder_ = other.folder_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasFile()) {
          file_ = other.file_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                folder_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                file_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object folder_ = "";
      /**
       * <pre>
       * Directory in which the media is contained
       * </pre>
       *
       * <code>optional string folder = 1;</code>
       * @return Whether the folder field is set.
       */
      public boolean hasFolder() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Directory in which the media is contained
       * </pre>
       *
       * <code>optional string folder = 1;</code>
       * @return The folder.
       */
      public java.lang.String getFolder() {
        java.lang.Object ref = folder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            folder_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Directory in which the media is contained
       * </pre>
       *
       * <code>optional string folder = 1;</code>
       * @return The bytes for folder.
       */
      public com.google.protobuf.ByteString
          getFolderBytes() {
        java.lang.Object ref = folder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          folder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Directory in which the media is contained
       * </pre>
       *
       * <code>optional string folder = 1;</code>
       * @param value The folder to set.
       * @return This builder for chaining.
       */
      public Builder setFolder(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        folder_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Directory in which the media is contained
       * </pre>
       *
       * <code>optional string folder = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFolder() {
        folder_ = getDefaultInstance().getFolder();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Directory in which the media is contained
       * </pre>
       *
       * <code>optional string folder = 1;</code>
       * @param value The bytes for folder to set.
       * @return This builder for chaining.
       */
      public Builder setFolderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        folder_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object file_ = "";
      /**
       * <pre>
       * Filename of media
       * </pre>
       *
       * <code>optional string file = 2;</code>
       * @return Whether the file field is set.
       */
      public boolean hasFile() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Filename of media
       * </pre>
       *
       * <code>optional string file = 2;</code>
       * @return The file.
       */
      public java.lang.String getFile() {
        java.lang.Object ref = file_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            file_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Filename of media
       * </pre>
       *
       * <code>optional string file = 2;</code>
       * @return The bytes for file.
       */
      public com.google.protobuf.ByteString
          getFileBytes() {
        java.lang.Object ref = file_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          file_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Filename of media
       * </pre>
       *
       * <code>optional string file = 2;</code>
       * @param value The file to set.
       * @return This builder for chaining.
       */
      public Builder setFile(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        file_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Filename of media
       * </pre>
       *
       * <code>optional string file = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFile() {
        file_ = getDefaultInstance().getFile();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Filename of media
       * </pre>
       *
       * <code>optional string file = 2;</code>
       * @param value The bytes for file to set.
       * @return This builder for chaining.
       */
      public Builder setFileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        file_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.sepp89117.goeasypro_android.gopro.Media)
    }

    // @@protoc_insertion_point(class_scope:com.sepp89117.goeasypro_android.gopro.Media)
    private static final com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media();
    }

    public static com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Media>
        PARSER = new com.google.protobuf.AbstractParser<Media>() {
      @java.lang.Override
      public Media parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Media> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Media> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sepp89117.goeasypro_android.gopro.ResponseGenericOuterClass.Media getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sepp89117_goeasypro_android_gopro_ResponseGeneric_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sepp89117_goeasypro_android_gopro_ResponseGeneric_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sepp89117_goeasypro_android_gopro_Media_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sepp89117_goeasypro_android_gopro_Media_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026response_generic.proto\022%com.sepp89117." +
      "goeasypro_android.gopro\"[\n\017ResponseGener" +
      "ic\022H\n\006result\030\001 \002(\01628.com.sepp89117.goeas" +
      "ypro_android.gopro.EnumResultGeneric\"%\n\005" +
      "Media\022\016\n\006folder\030\001 \001(\t\022\014\n\004file\030\002 \001(\t*\317\001\n\021" +
      "EnumResultGeneric\022\022\n\016RESULT_UNKNOWN\020\000\022\022\n" +
      "\016RESULT_SUCCESS\020\001\022\025\n\021RESULT_ILL_FORMED\020\002" +
      "\022\030\n\024RESULT_NOT_SUPPORTED\020\003\022!\n\035RESULT_ARG" +
      "UMENT_OUT_OF_BOUNDS\020\004\022\033\n\027RESULT_ARGUMENT" +
      "_INVALID\020\005\022!\n\035RESULT_RESOURCE_NOT_AVAILA" +
      "BLE\020\006"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sepp89117_goeasypro_android_gopro_ResponseGeneric_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sepp89117_goeasypro_android_gopro_ResponseGeneric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_sepp89117_goeasypro_android_gopro_ResponseGeneric_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_sepp89117_goeasypro_android_gopro_Media_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sepp89117_goeasypro_android_gopro_Media_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_sepp89117_goeasypro_android_gopro_Media_descriptor,
        new java.lang.String[] { "Folder", "File", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
