// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/turbo_transfer.proto

package com.sepp89117.goeasypro_android.gopro;

public final class TurboTransfer {
    private TurboTransfer() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 2,
                /* suffix= */ "",
                TurboTransfer.class.getName());
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface RequestSetTurboActiveOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.sepp89117.goeasypro_android.gopro.RequestSetTurboActive)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * Enable or disable Turbo Transfer feature
         * </pre>
         *
         * <code>required bool active = 1;</code>
         *
         * @return Whether the active field is set.
         */
        boolean hasActive();

        /**
         * <pre>
         * Enable or disable Turbo Transfer feature
         * </pre>
         *
         * <code>required bool active = 1;</code>
         *
         * @return The active.
         */
        boolean getActive();
    }

    /**
     * <pre>
     * *
     * Enable/disable display of "Transferring Media" UI
     *
     * Response: &#64;ref ResponseGeneric
     * </pre>
     * <p>
     * Protobuf type {@code com.sepp89117.goeasypro_android.gopro.RequestSetTurboActive}
     */
    public static final class RequestSetTurboActive extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:com.sepp89117.goeasypro_android.gopro.RequestSetTurboActive)
            RequestSetTurboActiveOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 29,
                    /* patch= */ 2,
                    /* suffix= */ "",
                    RequestSetTurboActive.class.getName());
        }

        // Use RequestSetTurboActive.newBuilder() to construct.
        private RequestSetTurboActive(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private RequestSetTurboActive() {
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.sepp89117.goeasypro_android.gopro.TurboTransfer.internal_static_open_gopro_RequestSetTurboActive_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.sepp89117.goeasypro_android.gopro.TurboTransfer.internal_static_open_gopro_RequestSetTurboActive_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive.class, com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive.Builder.class);
        }

        private int bitField0_;
        public static final int ACTIVE_FIELD_NUMBER = 1;
        private boolean active_ = false;

        /**
         * <pre>
         * Enable or disable Turbo Transfer feature
         * </pre>
         *
         * <code>required bool active = 1;</code>
         *
         * @return Whether the active field is set.
         */
        @java.lang.Override
        public boolean hasActive() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <pre>
         * Enable or disable Turbo Transfer feature
         * </pre>
         *
         * <code>required bool active = 1;</code>
         *
         * @return The active.
         */
        @java.lang.Override
        public boolean getActive() {
            return active_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasActive()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeBool(1, active_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(1, active_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive)) {
                return super.equals(obj);
            }
            com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive other = (com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive) obj;

            if (hasActive() != other.hasActive()) return false;
            if (hasActive()) {
                if (getActive()
                        != other.getActive()) return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasActive()) {
                hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getActive());
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseFrom(java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseFrom(java.nio.ByteBuffer data,
                                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseFrom(com.google.protobuf.ByteString data,
                                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseFrom(byte[] data,
                                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseFrom(java.io.InputStream input,
                                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseDelimitedFrom(java.io.InputStream input,
                                                                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseFrom(com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive parseFrom(com.google.protobuf.CodedInputStream input,
                                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * *
         * Enable/disable display of "Transferring Media" UI
         *
         * Response: &#64;ref ResponseGeneric
         * </pre>
         * <p>
         * Protobuf type {@code com.sepp89117.goeasypro_android.gopro.RequestSetTurboActive}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.sepp89117.goeasypro_android.gopro.RequestSetTurboActive)
                com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActiveOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.sepp89117.goeasypro_android.gopro.TurboTransfer.internal_static_open_gopro_RequestSetTurboActive_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.sepp89117.goeasypro_android.gopro.TurboTransfer.internal_static_open_gopro_RequestSetTurboActive_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive.class, com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive.Builder.class);
            }

            // Construct using com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive.newBuilder()
            Builder() {

            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                active_ = false;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.sepp89117.goeasypro_android.gopro.TurboTransfer.internal_static_open_gopro_RequestSetTurboActive_descriptor;
            }

            @java.lang.Override
            public com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive getDefaultInstanceForType() {
                return com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive.getDefaultInstance();
            }

            @java.lang.Override
            public com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive build() {
                com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive buildPartial() {
                com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive result = new com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.active_ = active_;
                    to_bitField0_ |= 0x00000001;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive) {
                    return mergeFrom((com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive other) {
                if (other == com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive.getDefaultInstance())
                    return this;
                if (other.hasActive()) {
                    setActive(other.getActive());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasActive()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                active_ = input.readBool();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private boolean active_;

            /**
             * <pre>
             * Enable or disable Turbo Transfer feature
             * </pre>
             *
             * <code>required bool active = 1;</code>
             *
             * @return Whether the active field is set.
             */
            @java.lang.Override
            public boolean hasActive() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <pre>
             * Enable or disable Turbo Transfer feature
             * </pre>
             *
             * <code>required bool active = 1;</code>
             *
             * @return The active.
             */
            @java.lang.Override
            public boolean getActive() {
                return active_;
            }

            /**
             * <pre>
             * Enable or disable Turbo Transfer feature
             * </pre>
             *
             * <code>required bool active = 1;</code>
             *
             * @param value The active to set.
             * @return This builder for chaining.
             */
            public Builder setActive(boolean value) {

                active_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Enable or disable Turbo Transfer feature
             * </pre>
             *
             * <code>required bool active = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearActive() {
                bitField0_ = (bitField0_ & ~0x00000001);
                active_ = false;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.sepp89117.goeasypro_android.gopro.RequestSetTurboActive)
        }

        // @@protoc_insertion_point(class_scope:com.sepp89117.goeasypro_android.gopro.RequestSetTurboActive)
        private static final com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive();
        }

        public static com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<RequestSetTurboActive>
                PARSER = new com.google.protobuf.AbstractParser<RequestSetTurboActive>() {
            @java.lang.Override
            public RequestSetTurboActive parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<RequestSetTurboActive> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RequestSetTurboActive> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.sepp89117.goeasypro_android.gopro.TurboTransfer.RequestSetTurboActive getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_open_gopro_RequestSetTurboActive_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_open_gopro_RequestSetTurboActive_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\024turbo_transfer.proto\022\nopen_gopro\"\'\n\025Re" +
                        "questSetTurboActive\022\016\n\006active\030\001 \002(\010"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_open_gopro_RequestSetTurboActive_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_open_gopro_RequestSetTurboActive_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_open_gopro_RequestSetTurboActive_descriptor,
                new java.lang.String[]{"Active",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}

