// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/turbo_transfer.proto

package com.sepp89117.goeasypro_android.gopro;

public final class TurboTransfer {
    private TurboTransfer() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface RequestSetTurboActiveOrBuilder extends
            // @@protoc_insertion_point(interface_extends:RequestSetTurboActive)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * Enable or disable Turbo Transfer feature
         * </pre>
         *
         * <code>required bool active = 1;</code>
         *
         * @return Whether the active field is set.
         */
        boolean hasActive();

        /**
         * <pre>
         * Enable or disable Turbo Transfer feature
         * </pre>
         *
         * <code>required bool active = 1;</code>
         *
         * @return The active.
         */
        boolean getActive();
    }

    /**
     * Protobuf type {@code RequestSetTurboActive}
     */
    public static final class RequestSetTurboActive extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:RequestSetTurboActive)
            RequestSetTurboActiveOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use RequestSetTurboActive.newBuilder() to construct.
        private RequestSetTurboActive(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        RequestSetTurboActive() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
            return new RequestSetTurboActive();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TurboTransfer.internal_static_com_sepp89117_goeasypro_android_gopro_RequestSetTurboActive_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TurboTransfer.internal_static_com_sepp89117_goeasypro_android_gopro_RequestSetTurboActive_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(TurboTransfer.RequestSetTurboActive.class, TurboTransfer.RequestSetTurboActive.Builder.class);
        }

        private int bitField0_;
        public static final int ACTIVE_FIELD_NUMBER = 1;
        private boolean active_ = false;

        /**
         * <pre>
         * Enable or disable Turbo Transfer feature
         * </pre>
         *
         * <code>required bool active = 1;</code>
         *
         * @return Whether the active field is set.
         */
        @java.lang.Override
        public boolean hasActive() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <pre>
         * Enable or disable Turbo Transfer feature
         * </pre>
         *
         * <code>required bool active = 1;</code>
         *
         * @return The active.
         */
        @java.lang.Override
        public boolean getActive() {
            return active_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasActive()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeBool(1, active_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(1, active_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TurboTransfer.RequestSetTurboActive)) {
                return super.equals(obj);
            }
            TurboTransfer.RequestSetTurboActive other = (TurboTransfer.RequestSetTurboActive) obj;

            if (hasActive() != other.hasActive()) return false;
            if (hasActive()) {
                if (getActive()
                        != other.getActive()) return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasActive()) {
                hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getActive());
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TurboTransfer.RequestSetTurboActive parseFrom(java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TurboTransfer.RequestSetTurboActive parseFrom(java.nio.ByteBuffer data,
                                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TurboTransfer.RequestSetTurboActive parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TurboTransfer.RequestSetTurboActive parseFrom(com.google.protobuf.ByteString data,
                                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TurboTransfer.RequestSetTurboActive parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TurboTransfer.RequestSetTurboActive parseFrom(byte[] data,
                                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TurboTransfer.RequestSetTurboActive parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TurboTransfer.RequestSetTurboActive parseFrom(java.io.InputStream input,
                                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TurboTransfer.RequestSetTurboActive parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TurboTransfer.RequestSetTurboActive parseDelimitedFrom(java.io.InputStream input,
                                                                             com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TurboTransfer.RequestSetTurboActive parseFrom(com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TurboTransfer.RequestSetTurboActive parseFrom(com.google.protobuf.CodedInputStream input,
                                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TurboTransfer.RequestSetTurboActive prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code RequestSetTurboActive}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:RequestSetTurboActive)
                TurboTransfer.RequestSetTurboActiveOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TurboTransfer.internal_static_com_sepp89117_goeasypro_android_gopro_RequestSetTurboActive_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TurboTransfer.internal_static_com_sepp89117_goeasypro_android_gopro_RequestSetTurboActive_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(TurboTransfer.RequestSetTurboActive.class, TurboTransfer.RequestSetTurboActive.Builder.class);
            }

            // Construct using TurboTransfer.RequestSetTurboActive.newBuilder()
            Builder() {

            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                active_ = false;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TurboTransfer.internal_static_com_sepp89117_goeasypro_android_gopro_RequestSetTurboActive_descriptor;
            }

            @java.lang.Override
            public TurboTransfer.RequestSetTurboActive getDefaultInstanceForType() {
                return TurboTransfer.RequestSetTurboActive.getDefaultInstance();
            }

            @java.lang.Override
            public TurboTransfer.RequestSetTurboActive build() {
                TurboTransfer.RequestSetTurboActive result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public TurboTransfer.RequestSetTurboActive buildPartial() {
                TurboTransfer.RequestSetTurboActive result = new TurboTransfer.RequestSetTurboActive(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(TurboTransfer.RequestSetTurboActive result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.active_ = active_;
                    to_bitField0_ |= 0x00000001;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                            int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                                            java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TurboTransfer.RequestSetTurboActive) {
                    return mergeFrom((TurboTransfer.RequestSetTurboActive) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TurboTransfer.RequestSetTurboActive other) {
                if (other == TurboTransfer.RequestSetTurboActive.getDefaultInstance()) return this;
                if (other.hasActive()) {
                    setActive(other.getActive());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasActive()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                active_ = input.readBool();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private boolean active_;

            /**
             * <pre>
             * Enable or disable Turbo Transfer feature
             * </pre>
             *
             * <code>required bool active = 1;</code>
             *
             * @return Whether the active field is set.
             */
            @java.lang.Override
            public boolean hasActive() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <pre>
             * Enable or disable Turbo Transfer feature
             * </pre>
             *
             * <code>required bool active = 1;</code>
             *
             * @return The active.
             */
            @java.lang.Override
            public boolean getActive() {
                return active_;
            }

            /**
             * <pre>
             * Enable or disable Turbo Transfer feature
             * </pre>
             *
             * <code>required bool active = 1;</code>
             *
             * @param value The active to set.
             * @return This builder for chaining.
             */
            public Builder setActive(boolean value) {

                active_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Enable or disable Turbo Transfer feature
             * </pre>
             *
             * <code>required bool active = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearActive() {
                bitField0_ = (bitField0_ & ~0x00000001);
                active_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:RequestSetTurboActive)
        }

        // @@protoc_insertion_point(class_scope:RequestSetTurboActive)
        private static final TurboTransfer.RequestSetTurboActive DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TurboTransfer.RequestSetTurboActive();
        }

        public static TurboTransfer.RequestSetTurboActive getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<RequestSetTurboActive>
                PARSER = new com.google.protobuf.AbstractParser<RequestSetTurboActive>() {
            @java.lang.Override
            public RequestSetTurboActive parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<RequestSetTurboActive> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RequestSetTurboActive> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public TurboTransfer.RequestSetTurboActive getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_sepp89117_goeasypro_android_gopro_RequestSetTurboActive_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_sepp89117_goeasypro_android_gopro_RequestSetTurboActive_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\032proto/turbo_transfer.proto\022%com.sepp89" +
                        "117.goeasypro_android.gopro\"\'\n\025RequestSe" +
                        "tTurboActive\022\016\n\006active\030\001 \002(\010"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_sepp89117_goeasypro_android_gopro_RequestSetTurboActive_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_sepp89117_goeasypro_android_gopro_RequestSetTurboActive_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_com_sepp89117_goeasypro_android_gopro_RequestSetTurboActive_descriptor,
                new java.lang.String[]{"Active",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
